### ISSUE TITLE
"Invalid indexing" error with mm(traj)

### ISSUE THREAD

**Issue by jorisvandenbossche** [ngort01/fuzzyMM#2]
I just tried the `mm` function on a GPS trajectory, but I get the following error:

```
> test = mm(g)
Error in `E<-`(`*tmp*`, value = integer(0)) : invalid indexing
```

I looked a little bit into it, and it seems the error is raised in the `create_drn` function. The bbox is generated correctly:

```
> bbox <- as.matrix(data.frame(min=c(59.92486, 10.71632), max=c(59.93475, 10.73141)))
> create_drn(bbox)
Error in `E<-`(`*tmp*`, value = integer(0)) : invalid indexing
```

It seems that inside `create_drn`, the generated url does not return any data.

**Comment by ngort01** [comment]
Hi,

I could just take a quick look at it.
It works if the bbox looks like this (long, lat)

```
as.matrix(data.frame(min=c(10.716320, 59.924860), max=c(10.731410, 59.934750)))
```

assuming the data from Oslo is what you want.
If that's not what you need let me know.

**Comment by jorisvandenbossche** [comment]
Thanks for the quick response!

Yes, I put the coordinates on the SpatialPointsDataFrame in the wrong order (`coordinates(traj) = c('lat', 'lon')` instead of `coordinates(traj) = c('lon', 'lat')`).

However, when I changes that, I got the following error:

```
> test = mm(traj)
Error in model.frame.default(value, object, na.action = na.fail) : 
  invalid type (NULL) for variable 'x'
```

This one seemed to be caused that `imp` functions tries to retrieve `coords.x1` and `coords.x2` from the `traj` (https://github.com/ngort01/fuzzyMM/blob/master/R/IMP.R#L11), while my coordinate columns are named lon and lat (therefore giving the NULL value). 
When I changed the names of the lon/lat columns, and ran again, now leading to this error:

```
> test = mm(g)
Error in rep(1:num.varinput, num.labels.input) : invalid 'times' argument
```

somewhere coming from inside `smp1` -> `predict(fis2, newdata)` -> `frbs`

**Comment by edzer** [comment]
`sp` has a method `coordnames` that returns the names of the coordinates, for this.

**Comment by ngort01** [comment]
Could you send me your trajectory? I will look into it then.

**Comment by jorisvandenbossche** [comment]
I uploaded an example as csv file to google drive: https://drive.google.com/file/d/0B3G70MlBnCgKcnVpSVA0bE9Ucmc/view?usp=sharing

Code I used:

```
library(lubridate)
library(fuzzyMM)

gpsfile = ".../GPS_DATA_BCM8/BCM8_123200320_20150428_143516.csv"

g = read.csv(gpsfile, stringsAsFactors=F)

g$datetime =  ymd_hms(g$datetime)
colnames(g) = c('time', 'coords.x2', 'coords.x1', 'alt', 'gps_fix', 'num_sats', 'GPS.Speed', 'GPS.Bearing', 'pdop', 'GPS.HDOP', 'vdop' )
coordinates(g) = c('coords.x1', 'coords.x2')
g@proj4string = CRS('+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ')

test = mm(g)
```

Thanks a lot for looking into it!

**Comment by ngort01** [comment]
I took a look at it and fixed some bugs now.

The trajectories I used originally had 2 fields for speed, "GPS.Speed" and "Speed" and at some points in the code I used the second one..

Another thing is that the algorithm uses an error region around GPS positions to find all street segments that may be used for matching. This had a fixed size leading to an error because some points in your trajectory were further away from any streets.
However, now you can manually change this size by passing it as an argument to the function.
For your trajectory 50 meters worked:

```
test = mm(g, plot=TRUE, err_region = 50)
```

Also the GPS.Speed should be converted to km/h.

```
g@data$GPS.Speed <- g@data$GPS.Speed * 3.6
```

Coordnames now also shouldn't matter anymore.

Unfortunately the result is not so accurate at some points.
![rplot](https://cloud.githubusercontent.com/assets/3532768/7446604/de476f00-f1dd-11e4-9b0a-45581702a57e.png)

Whole Code:

```
library(lubridate)
library(fuzzyMM)

gpsfile = ".../GPS_DATA_BCM8/BCM8_123200320_20150428_143516.csv"

g = read.csv(gpsfile, stringsAsFactors=F)

g$datetime =  ymd_hms(g$datetime)
colnames(g) = c('time', 'coords.x2', 'coords.x1', 'alt', 'gps_fix', 'num_sats', 'GPS.Speed', 'GPS.Bearing', 'pdop', 'GPS.HDOP', 'vdop' )
coordinates(g) = c('coords.x1', 'coords.x2')
g@proj4string = CRS('+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ')

g@data$GPS.Speed <- g@data$GPS.Speed * 3.6

test = mm(g, plot=TRUE, err_region = 50)
```

**Comment by jorisvandenbossche** [comment]
@ngort01 Thanks a lot! 
I can confirm it is now working.

The results are indeed not always so accurate. And the speed was already in km/h, but we were biking, so therefore the speeds are lower. And that is maybe also a reason that it is less accurate?

**Comment by ngort01** [comment]
Might be true. It got better after I converted it because I thought it's m/s.
